use pdc
go

drop table dbo.fechas_hoteles
drop table dbo.hoteles
drop table dbo.localidades
go

/* -----------------------------------------
   Tabla: localidades
   ----------------------------------------- */
create table dbo.localidades
(
 nro_localidad		integer			not null
					constraint PK__localidades__END primary key,
 localidad			varchar(100)	not null,
 cod_provincia		varchar(3)		not null
)
go

insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(1, 'AGUARAY', 'A')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(2, 'CAFAYATE', 'A')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(3, 'CAMPO QUIJANO', 'A')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(4, 'CERRILLOS', 'A')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(5, 'COLONIA SANTA ROSA', 'A')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(6, 'YACARA', 'A')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(7, 'YACAY', 'A')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(8, 'YACERA', 'A')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(9, 'YACIMIENTO TONONO', 'A')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(10, 'YACOCHUYA', 'A')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(11, 'YACONES', 'A')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(12, 'YACUY', 'A')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(13, 'YANCHUYA', 'A')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(14, 'YARIGUARENDA', 'A')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(15, 'YASQUIASME', 'A')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(16, 'YATASTO', 'A')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(17, 'YUCHAN', 'A')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(18, 'ZANJA HONDA', 'A')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(19, 'ZANJON', 'A')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(20, 'ZAPALLITO', 'A')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(21, '9 DE JULIO', 'B')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(22, 'ACASSUSO', 'B')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(23, 'ALBERTI', 'B')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(24, 'ALGARROBO', 'B')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(25, 'AMERICA', 'B')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(26, 'ARRECIFES', 'B')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(27, 'ARRIBEÑOS', 'B')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(28, 'ASCENCION', 'B')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(29, 'AVELLANEDA', 'B')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(30, 'AYACUCHO', 'B')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(31, 'AZUL', 'B')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(32, 'BAHIA BLANCA', 'B')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(33, 'BALCARCE', 'B')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(34, 'BANFIELD', 'B')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(35, 'BARADERO', 'B')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(36, 'BECCAR', 'B')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(37, 'BENITO JUAREZ', 'B')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(38, 'BERAZATEGUI', 'B')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(39, 'GENERAL BELGRANO', 'B')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(40, 'ZUBIAURRE', 'B')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(41, 'BUENA ESPERANZA', 'D')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(42, 'CARPINTERIA', 'D')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(43, 'CONCARAN', 'D')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(44, 'EL TRAPICHE', 'D')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(45, 'LA TOMA', 'D')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(46, 'MERLO', 'D')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(47, 'QUINES', 'D')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(48, 'SAN LUIS', 'D')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(49, 'SANTA ROSA DE CONLARA', 'D')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(50, 'TILISARAO', 'D')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(51, 'VILLA MERCEDES', 'D')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(52, 'VILLA SANTIAGO', 'D')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(53, 'VIRARCO', 'D')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(54, 'VISCACHERAS', 'D')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(55, 'VISTA ALEGRE', 'D')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(56, 'VISTA HERMOSA', 'D')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(57, 'VIVA LA PATRIA', 'D')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(58, 'VIZCACHERAS', 'D')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(59, 'VOLCAN ESTANZUELA', 'D')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(60, 'YACORO', 'D')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(61, 'BOVRIL', 'E')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(62, 'CHAJARI', 'E')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(63, 'COLON', 'E')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(64, 'COLONIA TRES DE FEBRERO', 'E')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(65, 'CONCEPCION DEL URUGUAY', 'E')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(66, 'CONCORDIA', 'E')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(67, 'CRESPO', 'E')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(68, 'DIAMANTE', 'E')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(69, 'FEDERAL', 'E')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(70, 'GENERAL RAMIREZ', 'E')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(71, 'GUALEGUAYCHU', 'E')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(72, 'HERNANDEZ', 'E')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(73, 'LA PAZ', 'E')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(74, 'LIBERTADOR SAN MARTIN', 'E')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(75, 'YERUA', 'E')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(76, 'YESO', 'E')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(77, 'YESO OESTE', 'E')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(78, 'YUQUERI', 'E')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(79, 'ZENON ROCA', 'E')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(80, 'ZONA DELTA DEL PARANA', 'E')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(81, 'AIMOGASTA', 'F')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(82, 'CHAMICAL', 'F')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(83, 'CHAÑAR', 'F')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(84, 'CHEPES', 'F')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(85, 'CHILECITO', 'F')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(86, 'LA RIOJA', 'F')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(87, 'LA TORDILLA', 'F')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(88, 'LAS PADERCITAS', 'F')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(89, 'OLTA', 'F')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(90, 'ULAPES', 'F')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(91, 'VERDE OLIVO', 'F')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(92, 'VILLA BUSTOS', 'F')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(93, 'VILLA CASANA', 'F')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(94, 'VILLA CHEPES', 'F')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(95, 'VILLA NIDIA', 'F')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(96, 'VILLA SAN JOSE DE VINCHINA', 'F')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(97, 'VILLA SANAGASTA', 'F')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(98, 'VILLA SANTA RITA', 'F')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(99, 'VILLA UNION', 'F')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(100, 'VINCHINA', 'F')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(101, 'YACU HURMANA', 'G')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(102, 'YACUCHIRI', 'G')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(103, 'YALAN', 'G')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(104, 'YANDA', 'G')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(105, 'YANTA', 'G')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(106, 'YASO', 'G')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(107, 'YESO ALTO', 'G')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(108, 'YLUMAMPA', 'G')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(109, 'YOLOHUASI', 'G')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(110, 'YUCHAN', 'G')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(111, 'YUCHANCITO', 'G')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(112, 'YULU HUASI', 'G')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(113, 'YUMAMPA', 'G')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(114, 'YUNTA POZO', 'G')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(115, 'YUTO YACA', 'G')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(116, 'YUTU YACO', 'G')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(117, 'ZANJA', 'G')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(118, 'ZANJON', 'G')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(119, 'ZAPI POZO', 'G')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(120, 'ZORRO HUARCUNA', 'G')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(121, 'AVIA TERAI', 'H')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(122, 'BARRANQUERAS', 'H')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(123, 'CHARATA', 'H')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(124, 'CORONEL DU GRATY', 'H')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(125, 'GANCEDO', 'H')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(126, 'GENERAL JOSE DE SAN MARTIN', 'H')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(127, 'GENERAL PINEDO', 'H')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(128, 'GENERAL VEDIA', 'H')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(129, 'JUAN JOSE CASTELLI', 'H')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(130, 'LAS BREÑAS', 'H')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(131, 'LAS PALMAS', 'H')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(132, 'MACHAGAI', 'H')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(133, 'MESON DE FIERRO', 'H')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(134, 'PAMPA DEL INDIO', 'H')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(135, 'PRESIDENCIA DE LA PLAZA', 'H')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(136, 'PRESIDENCIA ROQUE SAENZ PEÑA', 'H')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(137, 'RESISTENCIA', 'H')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(138, 'SAMUHÚ', 'H')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(139, 'TRES ISLETAS', 'H')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(140, 'ZUBERBHULER', 'H')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(141, 'BARREAL', 'J')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(142, 'CHIMBAS', 'J')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(143, 'DESAMPARADOS', 'J')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(144, 'IGLESIA', 'J')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(145, 'JACHAL', 'J')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(146, 'RAWSON', 'J')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(147, 'RIVADAVIA', 'J')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(148, 'SAN JUAN', 'J')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(149, 'SANTA LUCIA', 'J')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(150, 'TRES ESQUINAS', 'J')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(151, 'ULLUM', 'J')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(152, 'VILLA RUFINO GOMEZ', 'J')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(153, 'VILLA SAN ISIDRO', 'J')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(154, 'VILLA SANTA ANITA', 'J')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(155, 'VILLA SANTA PAULA', 'J')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(156, 'VILLA SARGENTO CABRAL', 'J')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(157, 'VOLCAN', 'J')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(158, 'YERBA BUENA', 'J')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(159, 'YOCA', 'J')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(160, 'ZAVALLA', 'J')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(161, 'ANDALGALA', 'K')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(162, 'BELEN', 'K')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(163, 'CHUMBICHA', 'K')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(164, 'FIAMBALA', 'K')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(165, 'LAS TEJAS DE VALLE VIEJO', 'K')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(166, 'LORO HUASI', 'K')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(167, 'POMAN', 'K')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(168, 'RECREO', 'K')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(169, 'SAN FERNANDO DEL VALLE DE CATAMARCA', 'K')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(170, 'SANTA MARIA', 'K')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(171, 'SANTA ROSA', 'K')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(172, 'SHINCAL', 'K')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(173, 'SIJAN', 'K')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(174, 'YAPES', 'K')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(175, 'YAQUICHO', 'K')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(176, 'YERBA BUENA', 'K')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(177, 'YOCAN', 'K')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(178, 'ZANJA', 'K')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(179, 'ZARCITO', 'K')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(180, 'ZARZA', 'K')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(181, 'CATRILO', 'L')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(182, 'COLONIA BARON', 'L')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(183, 'EDUARDO CASTEX', 'L')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(184, 'GENERAL ACHA', 'L')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(185, 'GENERAL PICO', 'L')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(186, 'GUATRACHE', 'L')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(187, 'INTENDENTE ALVEAR', 'L')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(188, 'MACACHIN', 'L')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(189, 'MAURICIO MAYER', 'L')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(190, 'QUEMU QUEMU', 'L')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(191, 'RANCUL', 'L')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(192, 'REALICO', 'L')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(193, 'SANTA ROSA', 'L')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(194, 'TRENEL', 'L')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(195, 'ZONA RURAL', 'L')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(196, 'ZONA RURAL  METILEO', 'L')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(197, 'ZONA RURAL DE MIRASOL', 'L')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(198, 'ZONA RURAL DE VERTIZ', 'L')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(199, 'ZONA RURAL DORILA', 'L')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(200, 'ZONA URBANA NORTE', 'L')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(201, 'BOWEN', 'M')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(202, 'CHACRAS DE CORIA', 'M')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(203, 'COQUIMBITO', 'M')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(204, 'DORREGO', 'M')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(205, 'EL NIHUIL', 'M')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(206, 'EUGENIO BUSTOS', 'M')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(207, 'GENERAL ALVEAR', 'M')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(208, 'GENERAL GUTIERREZ', 'M')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(209, 'GODOY CRUZ', 'M')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(210, 'GUAYMALLEN', 'M')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(211, 'LA CONSULTA', 'M')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(212, 'LA PAZ', 'M')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(213, 'LAS HERAS', 'M')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(214, 'LAVALLE VILLA TULUMAYA', 'M')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(215, 'LUJAN DE CUYO', 'M')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(216, 'MAIPU', 'M')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(217, 'MALARGÜE', 'M')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(218, 'ZANJON AMARILLO', 'M')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(219, 'ZANON CANAL', 'M')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(220, 'ZAPATA', 'M')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(221, '2 DE MAYO', 'N')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(222, '25 DE MAYO', 'N')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(223, 'APOSTOLES', 'N')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(224, 'ARISTOBULO DEL VALLE', 'N')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(225, 'AZARA', 'N')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(226, 'BERNARDO DE IRIGOYEN', 'N')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(227, 'CAMPO GRANDE', 'N')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(228, 'CAMPO VIERA', 'N')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(229, 'CANDELARIA', 'N')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(230, 'ELDORADO', 'N')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(231, 'GENERAL ALVEAR', 'N')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(232, 'JARDIN AMERICA', 'N')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(233, 'LEANDRO N ALEM', 'N')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(234, 'LOS HELECHOS', 'N')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(235, 'MONTECARLO', 'N')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(236, 'OBERA', 'N')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(237, 'POSADAS', 'N')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(238, 'YACUTINGA', 'N')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(239, 'YAPEYU CENTRO', 'N')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(240, 'YERBAL MAMBORETA', 'N')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(241, 'CLORINDA', 'P')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(242, 'EL COLORADO', 'P')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(243, 'ESTANISLAO DEL CAMPO', 'P')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(244, 'FORMOSA', 'P')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(245, 'GENERAL MANUEL BELGRANO', 'P')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(246, 'HERRADURA', 'P')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(247, 'INGENIERO GUILLERMO N JUAREZ', 'P')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(248, 'LAS LOMITAS', 'P')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(249, 'PIRANÉ', 'P')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(250, 'VILLA DOS TRECE', 'P')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(251, 'VILLA EMILIA', 'P')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(252, 'VILLA GENERAL URQUIZA', 'P')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(253, 'VILLA GRAL MANUEL BELGRANO', 'P')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(254, 'VILLA HERMOSA', 'P')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(255, 'VILLA LUCERO', 'P')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(256, 'VILLA MERCEDES', 'P')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(257, 'VILLA REAL', 'P')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(258, 'VIRASOL', 'P')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(259, 'YUNCA', 'P')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(260, 'ZORRILLA CUE', 'P')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(261, 'ALUMINE', 'Q')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(262, 'ANDACOLLO', 'Q')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(263, 'AÑELO', 'Q')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(264, 'CENTENARIO', 'Q')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(265, 'CHOS MALAL', 'Q')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(266, 'CONFLUENCIA DEL AGUIJON', 'Q')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(267, 'CUTRAL CO', 'Q')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(268, 'JUNIN DE LOS ANDES', 'Q')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(269, 'LAS LAJAS', 'Q')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(270, 'MARIANO MORENO', 'Q')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(271, 'NEUQUEN', 'Q')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(272, 'PICUN LEUFU', 'Q')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(273, 'PIEDRA DEL AGUILA', 'Q')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(274, 'PLAZA HUINCUL', 'Q')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(275, 'PLOTTIER', 'Q')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(276, 'RINCON DE LOS SAUCES', 'Q')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(277, 'SAN MARTIN DE LOS ANDES', 'Q')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(278, 'ZAINA YEGUA', 'Q')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(279, 'ZINGONE Y CIA M', 'Q')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(280, 'ZULEMITA', 'Q')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(281, 'ALLEN', 'R')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(282, 'BARDA DEL MEDIO', 'R')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(283, 'CATRIEL', 'R')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(284, 'CERVANTES', 'R')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(285, 'CHIMPAY', 'R')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(286, 'CHOELE CHOEL', 'R')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(287, 'CINCO SALTOS', 'R')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(288, 'CIPOLLETTI', 'R')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(289, 'CONTRALMIRANTE CORDERO', 'R')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(290, 'EL BOLSON', 'R')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(291, 'GENERAL ROCA', 'R')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(292, 'INGENIERO JACOBACCI', 'R')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(293, 'LAMARQUE', 'R')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(294, 'LAS GRUTAS', 'R')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(295, 'LUIS BELTRAN', 'R')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(296, 'MAQUINCHAO', 'R')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(297, 'RIO COLORADO', 'R')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(298, 'SAN CARLOS DE BARILOCHE', 'R')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(299, 'YAMINUE', 'R')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(300, 'YUQUINCHE', 'R')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(301, 'ALVAREZ', 'S')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(302, 'AREQUITO', 'S')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(303, 'ARMSTRONG', 'S')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(304, 'ARROYO SECO', 'S')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(305, 'ARRUFO', 'S')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(306, 'ARTEAGA', 'S')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(307, 'AVELLANEDA', 'S')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(308, 'CAÑADA DE GOMEZ', 'S')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(309, 'CANADA ROSQUIN', 'S')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(310, 'CAPITAN BERMUDEZ', 'S')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(311, 'CARCARAÑA', 'S')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(312, 'VILLA CONSTITUCION', 'S')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(313, 'VUELTA DEL PIRATA', 'S')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(314, 'WALVELBERG', 'S')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(315, 'WILDERMUTH', 'S')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(316, 'YAGUARETE', 'S')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(317, 'YAMANDU', 'S')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(318, 'ZADOCKHAN', 'S')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(319, 'ZAMPONI', 'S')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(320, 'ZANETTI', 'S')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(321, 'AGUILARES', 'T')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(322, 'YANGALLO', 'T')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(323, 'YANIMA', 'T')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(324, 'YAPACHIN', 'T')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(325, 'YAQUILO', 'T')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(326, 'YARAMI', 'T')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(327, 'YASYAMAYO', 'T')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(328, 'YATAPAYANA', 'T')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(329, 'YERBA HUASI', 'T')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(330, 'YMPAS', 'T')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(331, 'YONOPONGO', 'T')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(332, 'YONOPONGO SUD', 'T')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(333, 'YUCHACO', 'T')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(334, 'YUCUMANITA', 'T')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(335, 'YUMILLURA', 'T')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(336, 'YUNCA SUMA', 'T')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(337, 'ZANJON MASCIO', 'T')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(338, 'ZAPALLAR', 'T')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(339, 'ZAVALIA', 'T')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(340, 'ZURITA', 'T')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(341, 'COMODORO RIVADAVIA', 'U')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(342, 'DOLAVON', 'U')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(343, 'EPUYEN', 'U')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(344, 'ESQUEL', 'U')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(345, 'GAIMAN', 'U')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(346, 'GOBERNADOR COSTA', 'U')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(347, 'LAGO PUELO', 'U')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(348, 'PASO DE INDIOS', 'U')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(349, 'PLAYA UNION', 'U')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(350, 'PUERTO MADRYN', 'U')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(351, 'PUERTO PIRAMIDES', 'U')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(352, 'RADA TILLY', 'U')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(353, 'RAWSON', 'U')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(354, 'RIO MAYO', 'U')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(355, 'RIO PICO', 'U')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(356, 'SARMIENTO', 'U')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(357, 'TRELEW', 'U')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(358, 'TREVELIN', 'U')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(359, 'VILLA INES', 'U')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(360, 'VILLA LAGO RIVADAVIA', 'U')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(361, 'ASERRADERO ARROYO', 'V')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(362, 'BAHIA LAPATAIA', 'V')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(363, 'BASE AEREA TENIENTE MATIENZO', 'V')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(364, 'BASE BELGRANO', 'V')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(365, 'BASE BELGRANO 2', 'V')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(366, 'BASE BELGRANO 3', 'V')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(367, 'BASE CIENTIFICA TENIENTE JUBANY', 'V')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(368, 'BASE EJERCITO ESPERANZA', 'V')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(369, 'BASE EJERCITO PRIMAVERA', 'V')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(370, 'BASE EJERCITO SOBRAL', 'V')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(371, 'BASE ORCADAS', 'V')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(372, 'CABAÑA RUBY', 'V')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(373, 'CABO SAN PABLO', 'V')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(374, 'PUNTA MARIA', 'V')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(375, 'RIO GRANDE', 'V')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(376, 'SAN SEBASTIAN', 'V')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(377, 'SANTA INES', 'V')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(378, 'SECCION AVILES  ESTANCIA SAN J', 'V')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(379, 'TOLHUIN', 'V')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(380, 'USHUAIA', 'V')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(381, 'ALVEAR', 'W')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(382, 'BELLA VISTA', 'W')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(383, 'CONCEPCION', 'W')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(384, 'CORRIENTES', 'W')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(385, 'EMPEDRADO', 'W')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(386, 'ESQUINA', 'W')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(387, 'GOBERNADOR VIRASORO', 'W')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(388, 'GOYA', 'W')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(389, 'ITA IBATE', 'W')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(390, 'ITATI', 'W')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(391, 'ITUZAINGO', 'W')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(392, 'LA CRUZ', 'W')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(393, 'MONTE CASEROS', 'W')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(394, 'PASO DE LOS LIBRES', 'W')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(395, 'SALADAS', 'W')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(396, 'YTA PASO', 'W')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(397, 'YUQUERI', 'W')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(398, 'YURUCUA', 'W')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(399, 'ZAPALLAR', 'W')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(400, 'ZAPALLOS', 'W')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(401, 'ACHIRAS', 'X')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(402, 'ADELIA MARIA', 'X')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(403, 'AGUA DE ORO', 'X')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(404, 'ALCIRA GIGENA', 'X')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(405, 'ALEJANDRO ROCA', 'X')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(406, 'ALEJO LEDESMA', 'X')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(407, 'ALICIA', 'X')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(408, 'ALMAFUERTE', 'X')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(409, 'ALTA GRACIA', 'X')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(410, 'BELL VILLE', 'X')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(411, 'CÓRDOBA', 'X')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(412, 'LA CUMBRE', 'X')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(413, 'SANTA ROSA DE CALAMUCHITA', 'X')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(414, 'VILLA ALLENDE', 'X')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(415, 'VILLA CARLOS PAZ', 'X')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(416, 'VILLA DOLORES', 'X')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(417, 'VILLA GENERAL BELGRANO', 'X')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(418, 'VILLA MARIA', 'X')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(419, 'ZAPATA', 'X')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(420, 'ZAPOLOCO', 'X')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(421, 'CAIMANCITO', 'Y')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(422, 'EL CARMEN', 'Y')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(423, 'HUMAHUACA', 'Y')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(424, 'LA QUIACA', 'Y')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(425, 'LEDESMA', 'Y')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(426, 'LIBERTADOR GENERAL SAN MARTIN', 'Y')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(427, 'MONTERRICO', 'Y')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(428, 'PALPALÁ', 'Y')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(429, 'PERICO', 'Y')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(430, 'RIO BLANCO', 'Y')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(431, 'SAN PEDRO', 'Y')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(432, 'SAN SALVADOR DE JUJUY', 'Y')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(433, 'VOLCAN', 'Y')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(434, 'VOLCAN HIGUERA', 'Y')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(435, 'YACORAITE', 'Y')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(436, 'YALA DE MONTE CARMELO', 'Y')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(437, 'YAVI CHICO', 'Y')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(438, 'YERBA BUENA TILCARA', 'Y')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(439, 'YUTO', 'Y')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(440, 'ZAPLA', 'Y')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(441, '28 DE NOVIEMBRE', 'Z')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(442, 'CALETA OLIVIA', 'Z')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(443, 'CAÑADÓN SECO', 'Z')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(444, 'COMANDANTE LUIS PIEDRABUENA', 'Z')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(445, 'EL CALAFATE', 'Z')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(446, 'FITZ ROY', 'Z')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(447, 'GOBERNADOR GREGORES', 'Z')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(448, 'JARAMILLO', 'Z')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(449, 'LAS HERAS', 'Z')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(450, 'LOS ANTIGUOS', 'Z')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(451, 'PICO TRUNCADO', 'Z')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(452, 'PUERTO DESEADO', 'Z')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(453, 'PUERTO SAN JULIAN', 'Z')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(454, 'PUERTO SANTA CRUZ', 'Z')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(455, 'RIO GALLEGOS', 'Z')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(456, 'RIO TURBIO', 'Z')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(457, 'VENTISQUERO MORENO', 'Z')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(458, 'YACIMIENTO CERRO VANGUARDIA', 'Z')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(459, 'YEGUA MUERTA', 'Z')
insert into dbo.localidades(nro_localidad, localidad, cod_provincia)
values(460, 'ZANJON DEL PESCADO', 'Z')
go

/* -----------------------------------------
   Tabla: hoteles
   ----------------------------------------- */
create table dbo.hoteles
(
 nro_hotel		integer			not null
				constraint PK__hoteles__END primary key,
 hotel			varchar(100)	not null,
 nro_localidad	integer			not null
				constraint FK__hoteles__localidades__END references dbo.localidades
)
go

declare @nro_hotel		integer			= 1,
		@nro_localidad	integer,
		@localidad		varchar(100)

declare hoteles cursor
    for select nro_localidad,
	           localidad
		  from dbo.localidades
   open hoteles
  fetch hoteles into @nro_localidad, @localidad
  while @@fetch_status = 0
    begin
	  insert into dbo.hoteles(nro_hotel, hotel, nro_localidad)
	  values(@nro_hotel, 'HOTEL ' + @localidad + ' I', @nro_localidad),
	        (@nro_hotel + 1, 'HOTEL ' + @localidad + ' II', @nro_localidad)

      set @nro_hotel = @nro_hotel + 2
	  fetch hoteles into @nro_localidad, @localidad
	end
close hoteles
deallocate hoteles
go 

/* -----------------------------------------
   Tabla: fechas_hoteles
   ----------------------------------------- */
create table dbo.fechas_hoteles
(
 nro_hotel			integer			not null
					constraint FK__fechas_hoteles__hoteles__END references dbo.hoteles,
 fecha				date			not null,
 tipo_habitacion	char(1)			not null
					constraint CK__fechas_hoteles__tipo_habitacion__END check(tipo_habitacion in ('I', 'D', 'F')),
 hab_disponibles	smallint		not null,
 constraint PK__fechas_hoteles__END
			primary key(nro_hotel, fecha, tipo_habitacion)
)
go

declare @nro_hotel		integer,
        @cant_dias		smallint

declare fechas cursor
    for select nro_hotel
	      from dbo.hoteles
   open fechas
  fetch fechas into @nro_hotel
  while @@fetch_status = 0
    begin
	  set @cant_dias = -5

	  while @cant_dias <= 5
	    begin
	      insert into dbo.fechas_hoteles(nro_hotel, fecha, tipo_habitacion, hab_disponibles)
	      values(@nro_hotel, dateadd(day, @cant_dias, getdate()), 'I', 10 * rand()),
		        (@nro_hotel, dateadd(day, @cant_dias, getdate()), 'D', 20 * rand()),
		        (@nro_hotel, dateadd(day, @cant_dias, getdate()), 'F', 10 * rand())
	   
	      set @cant_dias = @cant_dias + 1
		end

	  fetch fechas into @nro_hotel
	end
close fechas
deallocate fechas
go 

/* -----------------------------------------
   Consulta de localidades
   ----------------------------------------- */
declare @cod_provincia	varchar(3) = 'X'

select nro_localidad,
       localidad
  from dbo.localidades (nolock)
 where cod_provincia = @cod_provincia
 order by localidad
go

/* -----------------------------------------
   Procedimiento: get_fechas_hoteles
   ----------------------------------------- */
create procedure dbo.get_fechas_hoteles
(
 @nro_localidad		integer,
 @fecha_desde		date,
 @fecha_hasta		date,
 @tipo_habitacion	char(1)	= 'T'
)
as
begin

  select hotel                = h.hotel,
         fecha                = convert(varchar(10), f.fecha, 103),
		 desc_tipo_habitacion = case tipo_habitacion
		                             when 'I'
									 then 'Individual'
									 when 'D'
									 then 'Doble'
									 when 'F'
									 then 'Familiar'
								end,
         tipo_habitacion      = f.tipo_habitacion,
		 hab_disponibles      = f.hab_disponibles,
		 nro_hotel            = f.nro_hotel
	from dbo.fechas_hoteles f (nolock)
	     join dbo.hoteles h (nolock)
		   on f.nro_hotel = h.nro_hotel
   where  h.nro_localidad    = @nro_localidad
     and  f.fecha           between @fecha_desde and @fecha_hasta
	 and (@tipo_habitacion   = 'T'
	  or  f.tipo_habitacion  = @tipo_habitacion)
	 and  f.hab_disponibles  > 0
   order by h.hotel,
            f.fecha,
			desc_tipo_habitacion

end
go

-- execute dbo.get_fechas_hoteles @nro_localidad=411, @fecha_desde='11 Dec 2016', @fecha_hasta='14 Dec 2016', @tipo_habitacion='D'
